import argparse

parser = argparse.ArgumentParser()
# general config
parser.add_argument('--type_dataset', type=str, default='jhu')
parser.add_argument('--output_dir', type=str, default='saved_jhu')
parser.add_argument('--crop_size', type=int, default=256)
parser.add_argument('--seed', type=int, default=1)
parser.add_argument('--save',  action='store_true')
# training config
parser.add_argument('--num_workers', type=int, default=2)
parser.add_argument('--print_freq', type=int, default=200)
parser.add_argument('--start_epoch', type=int, default=0)
parser.add_argument('--epochs', type=int, default=5000)
parser.add_argument('--pre', type=str, default=None) # pre-trained model
parser.add_argument('--batch_size', type=int, default=16)
parser.add_argument('--lr_step', type=int, default=1200)
parser.add_argument('--best_pred', type=int, default=1e5)
parser.add_argument('--gpu_id', type=str, default='0,1')
parser.add_argument('--lr', type=float, default=1e-4)
parser.add_argument('--weight_decay', type=float, default=5 * 1e-4)
parser.add_argument('--lr_backbone', default=1e-4, type=float)
parser.add_argument('--lr_drop', default=40, type=int)
parser.add_argument('--clip_max_norm', default=0.1, type=float)
# dataset config
parser.add_argument('--scale_aug', action='store_true')
parser.add_argument('--scale_type', type=int, default=0)
parser.add_argument('--scale_p', type=float, default=0.3)
parser.add_argument('--gray_aug', action='store_true')
parser.add_argument('--gray_p', type=float, default=0.1)
parser.add_argument('--dataset_file', default='crowd_data')
parser.add_argument('--device', default='cuda')
# testing config
parser.add_argument('--test_patch', action='store_true')
parser.add_argument('--channel_point', type=int, default=3)
parser.add_argument('--num_patch', type=int, default=1)
parser.add_argument('--min_num', type=int, default=-1)
parser.add_argument('--num_knn', type=int, default=4)
parser.add_argument('--test_per_epoch', type=int, default=20)
parser.add_argument('--threshold', type=float, default=0.35)
# demo config
parser.add_argument('--video_path', type=str, default='assets/demo.mp4')
# DDP config
parser.add_argument('--local_rank', type=int, default=-1)
parser.add_argument('--world_size', default=1, type=int)
parser.add_argument('--dist_url', default='env:// ')
parser.add_argument('--master_port', default=29501, type=int)
# model config
parser.add_argument('--frozen_weights', type=str, default=None)
parser.add_argument('--backbone', default='resnet50', type=str)
parser.add_argument('--dilation', action='store_true')
parser.add_argument('--position_embedding', default='sine', type=str, choices=('sine', 'learned'))
# transformer config
parser.add_argument('--enc_layers', default=6, type=int)
parser.add_argument('--dec_layers', default=6, type=int)
parser.add_argument('--dim_feedforward', default=2048, type=int)
parser.add_argument('--hidden_dim', default=256, type=int)
parser.add_argument('--dropout', default=0.1, type=float)
parser.add_argument('--nheads', default=8, type=int)
parser.add_argument('--num_queries', default=500, type=int)
parser.add_argument('--pre_norm', action='store_true')
parser.add_argument('--masks', action='store_true')
# loss config
parser.add_argument('--no_aux_loss', dest='aux_loss', action='store_false')
parser.add_argument('--mask_loss_coef', default=1, type=float)
parser.add_argument('--dice_loss_coef', default=1, type=float)
parser.add_argument('--cls_loss_coef', default=2, type=float)
parser.add_argument('--count_loss_coef', default=2, type=float)
parser.add_argument('--point_loss_coef', default=5, type=float)
parser.add_argument('--giou_loss_coef', default=2, type=float)
parser.add_argument('--focal_alpha', default=0.25, type=float)
# matcher config
parser.add_argument('--set_cost_class', default=2, type=float)
parser.add_argument('--set_cost_point', default=5, type=float)
parser.add_argument('--set_cost_giou', default=2, type=float)
args = parser.parse_args()
return_args = parser.parse_args()